version: "3.8"

services:
  edithra_ai:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=edithra_ai.py
      - FLASK_ENV=production
    depends_on:
      - redis
    restart: always

  redis:
    image: "redis:alpine"
    restart: always
